### ISSUE TITLE
turn every item in this list into an issue with appropriate emoji labels 🔥🤬

### ISSUE THREAD

**Issue by caxwel** [sidiousvic/yopardy#16]
_E M O J I  G U I D E_
🔥 Most wanted | 💅🏼 Easy | 😈 Fiddly | 🍪 Unneeded but fun | 🤬 You f*cking kidding me!?

**Comment by caxwel** [comment]
🥑🥑🥑C  O  M  P  L  E  T  E  D🥑🥑🥑

**Comment by sidiousvic** [comment]
Thank you 😈👍🏼🔥
